autonumber
Tredjepart -> AuthServer: /auth?clientID&clientSecret
activate AuthServer
AuthServer -> Tredjepart: AccessToken
deactivate AuthServer
Tredjepart -> SamtykkeSSO: create consent (Nin, AccessToken)
activate SamtykkeSSO
SamtykkeSSO -> Tredjepart: consentID
deactivate SamtykkeSSO
